### ISSUE TITLE
umd-packaged modules don't work with packaging systems that detect the `require` calls and assume they are global

### ISSUE THREAD

**Issue by petehunt** [ForbesLindesay/umd#10]
UMD-packaged modules are designed to work in any environment. Unfortunately they don't work in very many client-side packaging systems (I tried `browserify` and `requirejs`, `webpack` works).

Here's the scenario: `./x.js` requires `./y.js` and we do `browserify --standalone x x.js > ./temp/a.js`. If I require `a` from Node or drop it in a browser everything works. Great.

Now I create `./temp/b.js` which requires `./a.js` and I do `browserify b.js` from `./temp/`. It throws with `Error: Cannot find module './y'` because the word `require()` is used within the source still.

This is common behavior in many of the popular browser packaging systems I mentioned. They just look for calls to a function named `require()`.

My solution to this is to syntax transform the `require` literal when used as a function argument or function call to `muffin`. Would a pull request that does something like this (with a more mangled identifier) be accepted? It would require esprima.

**Comment by ForbesLindesay** [comment]
See #11.  I think this is best left as out of scope for this module.
