### ISSUE TITLE
Add support for Java 8 Nashorn Engine

### ISSUE THREAD

**Issue by winterbe** [ForbesLindesay/umd#22]
The template.js fails to evaluate on Java 8 Nashorn. Nashorn doesn't support any module system like AMD out of the box and there's neither `global` nor `window`. The global context is available via `this`.

Please add another fallback to `this` in template.js.

This refers to: https://github.com/facebook/react/issues/3037

**Comment by winterbe** [comment]
Awesome, thanks! :dancer:

**Comment by ForbesLindesay** [comment]
You will need to wait for https://github.com/substack/browser-pack/pull/49 before I expect it will get to react of course :)
