### ISSUE TITLE
Casing changes 

### ISSUE THREAD

**Issue by bendrucker** [ForbesLindesay/umd#24]
As mentioned in #23, I think there are some changes that should be made to casing:
- Use a module dependency for camel casing
- Throw if the name begins with an invalid leading character that's valid later in an identifier (e.g. a number) (instead of just stripping it)
- Throw if there are any invalid characters (instead of stripping them)

This could all get pulled out to a module as well.

Then there's the trickier issue of having automatic behavior at all. As mentioned in https://github.com/substack/node-browserify/pull/1210#issuecomment-92467065, it's potentially unexpected. But there are presumably a whole lot more people who ultimately want the behavior that's present now (camel casing) and would have to implement the casing on their own if it were removed as part of a major version. 

In order to make it customizable, browser-pack would have to be updated to allow an object for `opts.standalone` and Browserify's docs would need updating.

**Comment by zertosh** [comment]
Personally, I'm always hesitant about expanding API surface area - but that's @ForbesLindesay's call, plus he also has a commit bit in browser-pack :)

**Comment by manvalls** [comment]
If `opts.standalone` as an object becomes a thing, I'd love to see an `opts.standalone.raw` option which allows unaltered names, i.e:

```javascript
g['94,some-HOrrendous\'name'] = f();
```
