### ISSUE TITLE
simplify CLI arguments

### ISSUE THREAD

**Issue by jasonkarns** [ForbesLindesay/umd#26]
The CLI is great but at least two of the options provided could be derived from `package.json`

`name` can be taken from the package's `name`, and `source` would be from the package's `main`. This would leave only specifying the destination (or still piping to `STDOUT`)

I would love to be able to say just `umd | tee dist/module.js | uglifyjs > dist/module.min.js` for example.

**Comment by ForbesLindesay** [comment]
I'm more inclined to think that this module should be kept as simple as possible.  Interaction with package.json should be left to browserify

**Comment by jasonkarns** [comment]
Perhaps. But as a *nix cli utility, I'd expect it to follow the mantra of "sane defaults"

**Comment by ForbesLindesay** [comment]
I'm happy with the current behaviour.
